[project]
name = "minimit-llm"
version = "0.0.1"
dependencies = ["ruff", "pytest>=8.0.0"]

[tool.ruff]
line-length = 120
select = ["E", "F", "W", "I", "C", "B", "Q", "UP"]

[tool.pytest.ini_options]
testpaths = ["tests"]