[project]
name = "minimit-llm"
dependencies = ["ruff", "pytest>=8.0.0]

[tool.ruff]
line-lenght = 120
select = ["E", "F", "W", "I", "C", "B", "Q", "UP"]

[tool.pytest.ini_options]
testpaths = ["tests"]