name: "Build and Test"

on: [pull_request]

jobs:
    build:
        name: Setup&Build
        runs-on: ubuntu-latest
        container:
            image: python:3.12-slim
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            
          - name: Install dependencies
            run: |
                pip install --upgrade uv
                uv venv .venv
                . .venv/bin/activate
                uv pip install -r pyproject.toml
            
          - name: Ruff lint check
            uses: astral-sh/ruff-action@v1
            with:
                args: check .
            
          - name: Run tests
            run: |
                uv run pytest -v
